services:

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - mongodb

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build: ./backend
    command: celery -A backend worker --loglevel=info
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - mongodb

  mongodb:
    image: mongo:7
    container_name: promanage_mongo
    ports:
      - "27017:27017"